-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-03-17T20:35:41.781Z

CREATE TYPE "user_role" AS ENUM (
  'admin',
  'farmer',
  'service_provider'
);

CREATE TYPE "mission_status" AS ENUM (
  'ongoing',
  'complete',
  'canceled',
  'aborted'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "name" varchar,
  "surname" varchar,
  "role" user_role NOT NULL DEFAULT 'farmer',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "farms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "location_center" geometry,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "farm_ownerships" (
  "farm_id" int NOT NULL,
  "user_id" int NOT NULL,
  "ownership_percentage" decimal(5,2) NOT NULL,
  PRIMARY KEY ("farm_id", "user_id")
);

CREATE TABLE "fields" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farm_id" int NOT NULL,
  "name" varchar NOT NULL,
  "crop_name" varchar,
  "boundary" geometry
);

CREATE TABLE "mission_types" (
  "id" varchar PRIMARY KEY,
  "pilot_case" varchar,
  "partner" varhcar,
  "description" varchar
);

CREATE TABLE "missions" (
  "id" varchar PRIMARY KEY,
  "commander" int,
  "field" int,
  "type" varchar,
  "status" mission_status,
  "start" timestampz,
  "stop" timestampz,
  "date" timestampz
);

CREATE TABLE "pc1_weed" (
  "id" int PRIMARY KEY,
  "inspection" int,
  "name" varchar,
  "image" varchar,
  "confidence" float,
  "weed_loc" geometry,
  "is_sprayed" bool,
  "spray_time" timestmapz
);

CREATE TABLE "pc2_spraying_metadata" (
  "id" varchar PRIMARY KEY,
  "max_lat" float,
  "min_lat" float,
  "max_long" float,
  "min_long" float,
  "area_analyzed" float,
  "average_density" float,
  "crop_weed_correlation" float,
  "weed_liquid_correlation" float
);

CREATE TABLE "pc2_spraying_mission" (
  "id" varchar PRIMARY KEY,
  "properties" jsonb
);

CREATE TABLE "pc3_inspections" (
  "id" varchar PRIMARY KEY,
  "location" geometry,
  "biomass" float(1.2),
  "ndvi" float(1.2)
);

CREATE TABLE "pc4_pending" (
  "pending" int
);

CREATE TABLE "pc5_pending" (
  "pending" int
);

CREATE TABLE "pc6_pending" (
  "pending" int
);

COMMENT ON TABLE "users" IS 'Application users used for JWT authentication.';

COMMENT ON TABLE "farms" IS 'Farm registry. Ownership is defined in farm_ownerships.';

COMMENT ON TABLE "farm_ownerships" IS 'Many-to-many ownership relation between users and farms.';

COMMENT ON TABLE "fields" IS 'Field / plot registry. boundary is a PostGIS Polygon in SRID 4326.';

ALTER TABLE "farm_ownerships" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farm_ownerships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fields" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "missions" ADD FOREIGN KEY ("commander") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "missions" ADD FOREIGN KEY ("field") REFERENCES "fields" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "missions" ADD FOREIGN KEY ("type") REFERENCES "mission_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pc1_weed" ADD FOREIGN KEY ("inspection") REFERENCES "missions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pc2_spraying_metadata" ADD FOREIGN KEY ("id") REFERENCES "missions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pc2_spraying_mission" ADD FOREIGN KEY ("id") REFERENCES "missions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pc3_inspections" ADD FOREIGN KEY ("id") REFERENCES "missions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
