CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "user_role" AS ENUM (
  'system_admin',
  'farm_owner',
  'farm_manager',
  'worker',
  'third_party'
);

CREATE TYPE "access_level_enum" AS ENUM (
  'owner',
  'manager',
  'viewer'
);

CREATE TYPE "area_unit" AS ENUM (
  'hectare',
  'acre',
  'square_meter'
);

CREATE TYPE "device_type" AS ENUM (
  'sensor',
  'actuator',
  'camera',
  'controller',
  'robot'
);

CREATE TYPE "installation_type" AS ENUM (
  'weather_station',
  'irrigation_system',
  'drone_station',
  'sensor_hub'
);

CREATE TYPE "installation_status" AS ENUM (
  'active',
  'inactive',
  'maintenance',
  'error'
);

CREATE TYPE "device_status" AS ENUM (
  'online',
  'offline',
  'error'
);

CREATE TYPE "mission_type_enum" AS ENUM (
  'spraying',
  'scouting',
  'thinning',
  'seeding',
  'harvesting'
);

CREATE TYPE "trigger_operator" AS ENUM (
  '>',
  '>=',
  '<',
  '<=',
  '==',
  '!='
);

CREATE TYPE "run_status" AS ENUM (
  'success',
  'failed',
  'running',
  'skipped'
);

CREATE TABLE "farmers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone_number" varchar UNIQUE,
  "address" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "third_party_providers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" varchar NOT NULL,
  "service_type" varchar,
  "contact_email" varchar UNIQUE NOT NULL,
  "website" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" user_role NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL,
  "farmer_id" int,
  "third_party_provider_id" int
);

CREATE TABLE "user_farm_access" (
  "user_id" int,
  "farm_id" int,
  "access_level" access_level_enum NOT NULL,
  "granted_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "farm_id")
);

CREATE TABLE "api_keys" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key_hash" varchar UNIQUE NOT NULL,
  "provider_id" int NOT NULL,
  "scopes" JSONB NOT NULL,
  "expires_at" timestamp,
  "last_used_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "farms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farmer_id" int NOT NULL,
  "name" varchar NOT NULL,
  "location" geometry,
  "area" numeric(10,2),
  "unit" area_unit,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "crop_catalog" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "eppo_code" varchar UNIQUE NOT NULL,
  "scientific_name" varchar,
  "common_name" varchar,
  "type" varchar
);

CREATE TABLE "fields" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farm_id" int NOT NULL,
  "name" varchar,
  "crop_id" int,
  "soil_type" varchar,
  "area" numeric(10,2),
  "unit" area_unit,
  "polygon" geometry NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "devices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "installation_id" int,
  "name" varchar,
  "type" device_type NOT NULL,
  "model" varchar,
  "manufacturer" varchar,
  "serial_number" varchar UNIQUE,
  "firmware_version" varchar,
  "last_seen" timestamp,
  "status" device_status NOT NULL DEFAULT 'offline',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "robots" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int UNIQUE NOT NULL,
  "robot_name" varchar UNIQUE NOT NULL,
  "software_version" varchar
);

CREATE TABLE "installations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field_id" int NOT NULL,
  "type" installation_type NOT NULL,
  "name" varchar,
  "location" point NOT NULL,
  "installation_date" DATE,
  "status" installation_status NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "missions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "robot_id" int NOT NULL,
  "field_id" int NOT NULL,
  "user_id" int,
  "mission_type" mission_type_enum NOT NULL,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NOT NULL,
  "travelled_distance_m" numeric(10,2),
  "covered_area_m2" numeric(10,2),
  "sprayed_fluid_l" numeric(10,3),
  "target_fluid_density_lpha" numeric(10,2),
  "setpoint_pressure_bar" numeric(5,2),
  "cultivation_method" varchar,
  "inference_model" varchar,
  "context_crop_id" int,
  "target_id" int,
  "min_latitude" numeric(12,9),
  "max_latitude" numeric(12,9),
  "min_longitude" numeric(12,9),
  "max_longitude" numeric(12,9),
  "crop_weed_correlation" numeric(5,4),
  "weed_liquid_correlation" numeric(5,4),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "robot_state_timeseries" (
  "mission_id" bigint NOT NULL,
  "timestamp" timestamptz NOT NULL,
  "system_state" varchar,
  "latitude_rad" double precision,
  "longitude_rad" double precision,
  "pose_x_m" numeric,
  "pose_y_m" numeric,
  "pose_theta_rad" numeric,
  "speed_x_mps" numeric,
  "speed_y_mps" numeric,
  "speed_omega_radps" numeric,
  "unit0_fluid_l" numeric,
  "unit1_fluid_l" numeric,
  "unit2_fluid_l" numeric,
  "target_coverage_percent" numeric,
  "avoid_coverage_percent" numeric,
  PRIMARY KEY ("mission_id", "timestamp")
);

CREATE TABLE "mission_images" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mission_id" bigint NOT NULL,
  "timestamp" timestamptz NOT NULL,
  "image_url" varchar NOT NULL,
  "latitude" numeric(12,9),
  "longitude" numeric(12,9),
  "camera_id" int
);

CREATE TABLE "image_predictions" (
  "detection_id" UUID PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "image_id" bigint NOT NULL,
  "class_name" varchar NOT NULL,
  "confidence" numeric(5,4) NOT NULL,
  "x" numeric NOT NULL,
  "y" numeric NOT NULL,
  "width" numeric NOT NULL,
  "height" numeric NOT NULL
);

CREATE TABLE "agri_events" (
  "mission_id" bigint,
  "timestamp" timestamptz NOT NULL,
  "latitude" numeric(12,9) NOT NULL,
  "longitude" numeric(12,9) NOT NULL,
  "altitude" numeric,
  "event_type" varchar NOT NULL,
  "event_value" numeric NOT NULL,
  PRIMARY KEY ("mission_id", "timestamp", "event_type")
);

CREATE TABLE "measurement_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "default_unit" varchar NOT NULL,
  "description" TEXT
);

CREATE TABLE "sensor_readings" (
  "timestamp" timestamptz NOT NULL,
  "device_id" int NOT NULL,
  "measurement_type_id" int NOT NULL,
  "value" numeric(10,3) NOT NULL,
  PRIMARY KEY ("device_id", "timestamp")
);

CREATE TABLE "automations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farm_id" int NOT NULL,
  "name" varchar NOT NULL,
  "description" TEXT,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_by_user_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "automation_triggers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "automation_id" int NOT NULL,
  "device_id" int NOT NULL,
  "measurement_type_id" int NOT NULL,
  "operator" trigger_operator NOT NULL,
  "threshold_value" numeric(10,2) NOT NULL
);

CREATE TABLE "automation_actions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "automation_id" int NOT NULL,
  "target_device_id" int NOT NULL,
  "action_command" varchar NOT NULL,
  "action_value" varchar,
  "execution_order" int NOT NULL DEFAULT 1
);

CREATE TABLE "automation_runs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "automation_id" int NOT NULL,
  "started_at" timestamp NOT NULL DEFAULT (now()),
  "finished_at" timestamp,
  "status" run_status NOT NULL,
  "logs" TEXT
);

CREATE INDEX ON "sensor_readings" ("measurement_type_id", "timestamp");

COMMENT ON TABLE "farmers" IS 'Represents the legal owner or primary stakeholder of a farm.';

COMMENT ON TABLE "third_party_providers" IS 'For external companies or consultants who may require access to farm data.';

COMMENT ON TABLE "users" IS 'Central authentication table. A user represents an individual who can log in. A CHECK constraint should ensure only one of farmer_id or third_party_provider_id is set. Both can be NULL for system-level users.';

COMMENT ON TABLE "user_farm_access" IS 'Junction table to manage which user can access which farm and at what level. This is key for multi-tenancy.';

COMMENT ON TABLE "api_keys" IS 'Manages programmatic access for third-party services. Scopes define what data the key is authorized to access.';

COMMENT ON TABLE "farms" IS 'Represents a single farm. The farmer_id denotes the primary owner.';

COMMENT ON TABLE "crop_catalog" IS 'A standardized dictionary for crops, weeds, and other plants. Using a recognized standard like EPPO codes (e.g., "DAUCA" for Carrot) is crucial for interoperability.';

COMMENT ON TABLE "fields" IS 'A single, continuous piece of land within a farm. The `polygon` field is essential for storing its exact geospatial boundaries.';

COMMENT ON TABLE "devices" IS 'Master table for all physical hardware assets. Specific device types like robots have their own dedicated tables with more attributes.';

COMMENT ON TABLE "robots" IS 'Extends the `devices` table with attributes specific to autonomous robots, such as their unique name and software version.';

COMMENT ON TABLE "installations" IS 'Represents a physical installation in a field, which can host multiple devices. For example, a "Weather Station" might host temperature and humidity sensors.';

COMMENT ON TABLE "missions" IS 'Core table for logging robotic operations. It stores the summary data from files like `UC2/Ecorobotix/mission_data.json` and `UC2/Ecorobotix/mission_metadata.json`.';

COMMENT ON TABLE "robot_state_timeseries" IS 'Stores high-volume, high-frequency state data from a robot during a mission (from `UC2/Ecorobotix/mission_state_time_series.csv`). For massive scale, this table is a primary candidate for a dedicated time-series database like TimescaleDB.';

COMMENT ON TABLE "mission_images" IS 'A log of all images captured during a mission, linking them to a specific time and place. See sample: `UC5 & UC6/EUT/thinning_image.png`';

COMMENT ON TABLE "image_predictions" IS 'Stores the output of computer vision models (e.g., from `UC5 & UC6/EUT/thinning_output.json`). Each row is a single detected object within a mission image.';

COMMENT ON TABLE "agri_events" IS 'Flexible table for other time-series data streams from a mission, like the sample detection counts from `UC3 & UC4/sample_file_uc3_uc4.csv`.';

COMMENT ON TABLE "measurement_types" IS 'Defines the standardized types of sensor measurements that can be recorded, e.g., "temperature", "ph_level".';

COMMENT ON TABLE "sensor_readings" IS 'Stores time-series data from stationary sensors. Similar to robot_state_timeseries, this can grow very large and may benefit from a time-series database solution in the long term.';

COMMENT ON TABLE "automations" IS 'Defines a named automation rule, which consists of triggers and actions.';

COMMENT ON TABLE "automation_triggers" IS 'The "IF" part of an automation rule. e.g., IF sensor "X" temperature > 30°C.';

COMMENT ON TABLE "automation_actions" IS 'The "THEN" part of an automation rule. e.g., THEN turn on actuator "Y".';

COMMENT ON TABLE "automation_runs" IS 'A log of every time an automation is triggered and executed.';

ALTER TABLE "users" ADD FOREIGN KEY ("farmer_id") REFERENCES "farmers" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("third_party_provider_id") REFERENCES "third_party_providers" ("id");

ALTER TABLE "user_farm_access" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_farm_access" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id");

ALTER TABLE "api_keys" ADD FOREIGN KEY ("provider_id") REFERENCES "third_party_providers" ("id");

ALTER TABLE "farms" ADD FOREIGN KEY ("farmer_id") REFERENCES "farmers" ("id");

ALTER TABLE "fields" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id");

ALTER TABLE "fields" ADD FOREIGN KEY ("crop_id") REFERENCES "crop_catalog" ("id");

ALTER TABLE "devices" ADD FOREIGN KEY ("installation_id") REFERENCES "installations" ("id");

ALTER TABLE "robots" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "installations" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "missions" ADD FOREIGN KEY ("robot_id") REFERENCES "robots" ("id");

ALTER TABLE "missions" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "missions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "missions" ADD FOREIGN KEY ("context_crop_id") REFERENCES "crop_catalog" ("id");

ALTER TABLE "missions" ADD FOREIGN KEY ("target_id") REFERENCES "crop_catalog" ("id");

ALTER TABLE "robot_state_timeseries" ADD FOREIGN KEY ("mission_id") REFERENCES "missions" ("id");

ALTER TABLE "mission_images" ADD FOREIGN KEY ("mission_id") REFERENCES "missions" ("id");

ALTER TABLE "image_predictions" ADD FOREIGN KEY ("image_id") REFERENCES "mission_images" ("id");

ALTER TABLE "agri_events" ADD FOREIGN KEY ("mission_id") REFERENCES "missions" ("id");

ALTER TABLE "sensor_readings" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "sensor_readings" ADD FOREIGN KEY ("measurement_type_id") REFERENCES "measurement_types" ("id");

ALTER TABLE "automations" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id");

ALTER TABLE "automations" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "automation_triggers" ADD FOREIGN KEY ("automation_id") REFERENCES "automations" ("id");

ALTER TABLE "automation_triggers" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "automation_triggers" ADD FOREIGN KEY ("measurement_type_id") REFERENCES "measurement_types" ("id");

ALTER TABLE "automation_actions" ADD FOREIGN KEY ("automation_id") REFERENCES "automations" ("id");

ALTER TABLE "automation_actions" ADD FOREIGN KEY ("target_device_id") REFERENCES "devices" ("id");

ALTER TABLE "automation_runs" ADD FOREIGN KEY ("automation_id") REFERENCES "automations" ("id");
